# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Querylet-Output-Excel-XLS
version:      0.13
version_from: lib/Querylet/Output/Excel/XLS.pm
installdirs:  site
requires:
    Querylet::Output:              0.24
    Querylet::Query:               0.28
    Spreadsheet::WriteExcel:       2.04
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
